repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
        exclude: 'pagebreak\.lua'
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: ["--ignore", "docs/_*.md"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.11.1
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.47.0
          - eslint-plugin-toml@0.5.0
        files: \.toml$ # Only lint toml files
        types: [file]
        args: ["--fix"]
  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args: ["--python-folders", "src"]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.0
    hooks:
      - id: sqlfluff-fix
      - id: sqlfluff-lint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types_or: [python, markdown]
        additional_dependencies: [tomli]
  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.12"
    hooks:
      - id: vulture
        args: ["src", "--min-confidence=80"]
  - repo: https://github.com/Casper321/reST-docstring-checker
    rev: v0.0.4
    hooks:
      - id: rest-docstring-checker
        args: ["--strict"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.2
    hooks:
      - id: gitleaks
  # Ensure parity by running `pyright` locally.
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: bash -c 'pyright src tests'
        language: system
        types: [python]
        require_serial: true
  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: bash -c '
          pip-audit
          --ignore-vuln PYSEC-2022-43145'
        language: system
        require_serial: true
