[project]
name = "competetive-programming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [ "pytest>=8.4.1", ]

[dependency-groups]
dev = [
    "pip-audit>=2.9.0",
    "pyright>=1.1.404",
]
